version: '3.0'

services:
  webserver:
    image: 'nginx:alpine'
    container_name: 'study.patterns.nginx'
    working_dir: '/var/www'
    volumes:
      - '.:/var/www'
      - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - 8080:80

  php:
    build: 'docker/php'
    container_name: 'study.patterns.php'
    working_dir: '/var/www'
    volumes:
      - '.:/var/www'

  mysql:
    image: 'mysql:8.0'
    container_name: 'study.patterns.mysql'
    working_dir: /var/www
    restart: always
    volumes:
      - '.:/var/www'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=patterns
      - MYSQL_USER=pic
      - MYSQL_PASSWORD=patternstudy
    ports:
      - '3306:3306'
    
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: 'study.patterns.phpMyAdmin'
    restart: always
    ports:
      - 8082:80
    environment:
      - PMA_ARBITRARY=1